# Generated by Django 3.2.4 on 2021-06-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='current amount'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='initial_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='initial amount'),
        ),
    ]
