# Generated by Django 3.2.4 on 2021-06-24 18:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
                'db_table': 'currency',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('is_debit', models.BooleanField(verbose_name='is debit')),
            ],
            options={
                'verbose_name': 'transaction category',
                'verbose_name_plural': 'transaction categories',
                'db_table': 'transaction_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='amount')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='date and time')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('receipt', models.ImageField(blank=True, default=None, upload_to=finance.models.user_directory_path, verbose_name='receipt')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.transactioncategory', verbose_name='category')),
                ('currency', models.ForeignKey(default=finance.models.get_ruble_currency, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.currency', verbose_name='currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactios',
                'db_table': 'transaction',
                'ordering': ['datetime'],
            },
        ),
    ]
