# Generated by Django 3.2.4 on 2021-06-27 19:21

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['datetime'], 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
        migrations.CreateModel(
            name='PeriodicTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='end date')),
                ('pay_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='pay day')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='amount')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_transactions', to='finance.transactioncategory', verbose_name='category')),
                ('currency', models.ForeignKey(default=finance.models.get_ruble_currency, on_delete=django.db.models.deletion.CASCADE, related_name='periodic_transactions', to='finance.currency', verbose_name='currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_transactions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'periodic transaction',
                'verbose_name_plural': 'periodic transactions',
                'db_table': 'periodic_transaction',
                'ordering': ['pay_day'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='periodic_transaction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.periodictransaction', verbose_name='periodic transaction'),
        ),
    ]
