# Generated by Django 3.2.4 on 2021-06-29 11:45

from django.db import migrations
from django.db.models import Q

TRANSACTIONS_CATEGORY_DEBIT_TUPLE = (
    'Заработная плата',
    'Пенсия',
    'Стипендия',
    'Призовые / выигрыши',
    'Деньги от сдачи в аренду',
    'Кэшбэки и % от банков',
    'Инвестиции',
    'Подарки',
)

TRANSACTIONS_CATEGORY_CREDIT_TUPLE = (
    'Продукты',
    'Кафе и рестораны',
    'Обучение',
    'Развлечения',
    'Путешествия',
    'Здоровье и фитнес',
    'Аптеки',
    'Красота',
    'Одежда и обувь',
    'Общественный транспорт',
    'Такси',
    'Машина',
    'Детские товары',
    'Товары для животных',
    'Электроника и техника',
)


def apply_migration(apps, schema_editor):
    TransactionCategory = apps.get_model('finance', 'TransactionCategory')
    transaction_category_list = [
        TransactionCategory(name=name, is_debit=True)
        for name in TRANSACTIONS_CATEGORY_DEBIT_TUPLE
    ]
    transaction_category_list.extend((
        TransactionCategory(name=name, is_debit=False)
        for name in TRANSACTIONS_CATEGORY_CREDIT_TUPLE
    ))
    TransactionCategory.objects.bulk_create(transaction_category_list)


def revert_migration(apps, schema_editor):
    TransactionCategory = apps.get_model('finance', 'TransactionCategory')
    TransactionCategory.objects.filter(
        (Q(name__in=TRANSACTIONS_CATEGORY_DEBIT_TUPLE) & Q(is_debit=True)) |
        (Q(name__in=TRANSACTIONS_CATEGORY_CREDIT_TUPLE) & Q(is_debit=False))
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_periodic_transaction'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
