# Generated by Django 3.2.4 on 2021-07-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_transaction_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodictransaction',
            options={'ordering': ['-pay_day'], 'verbose_name': 'periodic transaction', 'verbose_name_plural': 'periodic transactions'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-datetime'], 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
    ]
